name: ğŸš€ Publish to NuGet.org

on:
  release:
    types: [published]  # GitHub'da yeni bir "Release" yayÄ±nlandÄ±ÄŸÄ±nda tetiklenir

permissions:
  id-token: write       # OIDC kimlik doÄŸrulamasÄ± iÃ§in gerekli
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        dotnet-version: [8.0.x, 9.0.x]

    steps:
      # 1ï¸âƒ£ Repo'yu al
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2ï¸âƒ£ .NET SDK'yÄ± kur
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # 3ï¸âƒ£ Restore, Build ve Pack (tek adÄ±mda)
      - name: Build and Pack
        run: |
          cd src
          dotnet restore StronglyTypedIds.sln
          dotnet build StronglyTypedIds.sln --configuration Release --no-restore
          dotnet pack ErginWebDev.StronglyTypedIds/ErginWebDev.StronglyTypedIds.csproj --configuration Release --no-build --output ../nupkg
      
      # 4ï¸âƒ£ NuGet Login
      - name: NuGet Login
        uses: NuGet/login@v1
        id: login
        with:
          user: ErginTIRAVOGLU

      # 6ï¸âƒ£ Trusted Publishing ile otomatik NuGet yayÄ±nlama
      - name: Publish to NuGet.org (Trusted Publishing)
        run: dotnet nuget push ./nupkg/*.nupkg --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://www.nuget.org/api/v2/package


 

 